name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: npm install
      
      - run: npm run lint
      
      - run: npm test
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      # Start Xvfb (virtual display server) for headed browser tests
      - name: Start xvfb
        run: |
          Xvfb :99 -screen 0 1280x800x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          
      # Run Playwright tests in headed mode (with virtual display)
      - name: Run Playwright tests
        run: npx playwright test
