name: CI & Test Badges

description: >
  Runs lint, unit tests, and e2e tests for the Chrome extension. Updates a public Gist for dynamic Shields.io test badges.

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-badge:
    name: Lint, Test, and Update Badge
    runs-on: ubuntu-latest
    env:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      GIST_ID: b417ceac6cfcf12a0910ef90196e7512
      GIST_FILENAME: tests-badge.json
      REPO_KEY: screen-capture-extension
      GIST_URL: https://api.github.com/gists/b417ceac6cfcf12a0910ef90196e7512
      GIST_RAW: https://gist.githubusercontent.com/briang123/b417ceac6cfcf12a0910ef90196e7512/raw/tests-badge.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint source code
        run: npm run lint

      - name: Run unit tests (Vitest) and count passing
        run: |
          npx vitest run --reporter=json > unit-test-results.json || true
          jq '[.testResults[].assertionResults[] | select(.status=="passed")] | length' unit-test-results.json > unit-passing.txt

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start Xvfb for headless browser tests
        run: |
          Xvfb :99 -screen 0 1280x800x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run e2e tests (Playwright) and count passing
        run: |
          npx playwright test --reporter=json > e2e-test-results.json 2> playwright-error.log || true
          if jq empty e2e-test-results.json 2>/dev/null; then
            jq '[.suites[].specs[].tests[] | select(.results[].status=="passed")] | length' e2e-test-results.json > e2e-passing.txt
          else
            echo 0 > e2e-passing.txt
          fi

      - name: Prepare badge JSON for Gist
        run: |
          UNIT_PASSING=$(cat unit-passing.txt)
          E2E_PASSING=$(cat e2e-passing.txt)
          jq --null-input \
            --arg repo "$REPO_KEY" \
            --arg unit_label "unit tests" \
            --arg unit_msg "$UNIT_PASSING passing" \
            --arg e2e_label "e2e tests" \
            --arg e2e_msg "$E2E_PASSING passing" \
            '{
              ($repo): {
                unit: {label: $unit_label, message: $unit_msg, color: "brightgreen"},
                e2e: {label: $e2e_label, message: $e2e_msg, color: "brightgreen"}
              }
            }' > tests-badge.json

      - name: Update Shields.io test badge Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ env.GIST_ID }}
          file_path: tests-badge.json
          gist_file_name: tests-badge.json
